### ISSUE TITLE
Error when submitting remaining observations for data_participant1.nt

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/solid-stream-aggregator-demo#2]
When I submit all remaining observations for `data_participant1.nt` in [this step](https://github.com/argahsuknesib/ssa-demo#starting-the-webapp-to-load), I get the following error:

```shell
***
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

Node.js v18.12.1
```

**Comment by argahsuknesib** [comment]
I am on Node v16.18.0

Quite strange, because it is a classic case of `works on my machine`.
The loading library is from the challenge https://github.com/solidLabResearch/challenges/issues/82 so maybe @svrstich has an idea or if he faced this issue?

**Comment by pheyvaer** [comment]
The issue happens when I don't submit a single observation first, but submit all remaining observations immediately. I skipped step 14 which says to first do 3 single observations. Thus, I should not skip step 14! 😄

**Comment by argahsuknesib** [comment]
The issue will be resolved completely with resolving the issue https://github.com/SolidLabResearch/LDES-in-SOLID-Semantic-Observations-Replay/issues/17
